### ISSUE TITLE
Long Category names break runner summary on small screens

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#110]
It's probably better to use a table to show the runner summary instead of pre-formatted text.

![image](https://user-images.githubusercontent.com/20268890/82292273-e42f0c00-99aa-11ea-9e44-0c62ba4df687.png)

**Comment by Avasam** [comment]
Preformatted text comes from the backend, it's dumb, I know, and I'm not touching it with a 10-foot pole anytime soon. Ah the wonders caused by a lack of knowledge of any programming best practices at the time (that and cannibalizing my old WoW Log Analyzer, which there are still traces of in the code).

I can easily implement a quick workaround in the frontend that will split the strings into arrays, allowing me to build a table.
