### ISSUE TITLE
Last updated coloring might be too strict

### ISSUE THREAD

**Issue by shenef** [Avasam/speedrun.com_global_scoreboard_webapp#93]
Since there is no automatic updating of the dataset most data will be colored in yellow or red most of the time. Aside from that it makes the site seem like it isn't used much and i think it's too strict in the first place since most people don't upload more than one run per week.
To reduce that effect i'd propose to change the coloring to this scheme:
**Blue:** This week
**Green:** This month
**Yellow:** Last 3 months
**Red:** Over 3 months

**Comment by Avasam** [comment]
Blue should follow the update/time restriction (which is 24h right now). I've actually thought about making it longer in the past, for the same reason `most people don't upload more than one run per week`.
As a whole I agree with your suggestion. Two things will need to be completed first:
- #84 (Allow results to be seen without having to update)
- I should make those times config-based rather than a hardcoded number of days.
